### PR TITLE
fixed spawn test

### PR DESCRIPTION
**Pull request by elenash**
Created a PR to check how jenkins works.

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 1 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//3/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-pmix-pr/3/

**Comment by rhc54** [comment]
@elenash Hi Elena

Is this intended to force an error so you can check the tests? It looks to me like the change to pmix_server is incorrect as the nspace is already in the returned info and doesn't need to be explicitly added. My spawn test is passing - I suspect any issue is actually in the test.

**Comment by elenash** [comment]
@rhc54 Hi Ralph, yes, I've already noticed that, investigating this issue in test currently. I will update this commit when ready.

**Comment by mellanox-github** [comment]
* Coverity found 1 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//4/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-pmix-pr/4/

**Comment by elenash** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//5/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-pmix-pr/5/


**Build Log**
*last 50 lines*

 ```
[...truncated 1938 lines...]
++ export FPATH
++ INCLUDE=/hpc/local/opt/valgrind-3.9.0/include
++ export INCLUDE
++ LD_LIBRARY_PATH=/hpc/local/opt/valgrind-3.9.0/lib
++ export LD_LIBRARY_PATH
++ LIBRARY_PATH=/hpc/local/opt/valgrind-3.9.0/lib
++ export LIBRARY_PATH
++ LOADEDMODULES=tools/hpc:tools/valgrind
++ export LOADEDMODULES
++ MANPATH=/hpc/local/opt/valgrind-3.9.0/man:/usr/share/man
++ export MANPATH
++ PATH=/hpc/local/opt/valgrind-3.9.0/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
++ export PATH
++ _LMFILES_=/hpc/local/etc/modulefiles/tools/hpc:/hpc/local/etc/modulefiles/tools/valgrind
++ export _LMFILES_
+ vg_opt='--tool=memcheck --leak-check=full --error-exitcode=0 --trace-children=yes  --trace-children-skip=*/sed,*/collect2,*/gcc,*/cat,*/rm,*/ls --track-origins=yes --xml=yes --xml-file=valgrind.xml --fair-sched=try --gen-suppressions=all'
+ valgrind --tool=memcheck --leak-check=full --error-exitcode=0 --trace-children=yes '--trace-children-skip=*/sed,*/collect2,*/gcc,*/cat,*/rm,*/ls' --track-origins=yes --xml=yes --xml-file=valgrind.xml --fair-sched=try --gen-suppressions=all ./pmix_test -n 4 --ns-dist 3:1 --fence '[db | 0:;1:3]'
pmix_test.c:main: Test finished OK!
+ valgrind --tool=memcheck --leak-check=full --error-exitcode=0 --trace-children=yes '--trace-children-skip=*/sed,*/collect2,*/gcc,*/cat,*/rm,*/ls' --track-origins=yes --xml=yes --xml-file=valgrind.xml --fair-sched=try --gen-suppressions=all ./pmix_test -n 4 --job-fence -c
pmix_test.c:main: Test finished OK!
+ valgrind --tool=memcheck --leak-check=full --error-exitcode=0 --trace-children=yes '--trace-children-skip=*/sed,*/collect2,*/gcc,*/cat,*/rm,*/ls' --track-origins=yes --xml=yes --xml-file=valgrind.xml --fair-sched=try --gen-suppressions=all ./pmix_test -n 2 --test-publish
pmix_test.c:main: Test finished OK!
+ valgrind --tool=memcheck --leak-check=full --error-exitcode=0 --trace-children=yes '--trace-children-skip=*/sed,*/collect2,*/gcc,*/cat,*/rm,*/ls' --track-origins=yes --xml=yes --xml-file=valgrind.xml --fair-sched=try --gen-suppressions=all ./pmix_test -n 2 --test-spawn
[jenkins01:29017] SPAWN_CBFUNC: 0 foobar
[jenkins01:29017] SPAWN_CBFUNC: 0 foobar
[jenkins01:29017] SPAWN_CBFUNC: 0 foobar
[jenkins01:29017] SPAWN_CBFUNC: 0 foobar
pmix_test.c:main: Test finished OK!
+ valgrind --tool=memcheck --leak-check=full --error-exitcode=0 --trace-children=yes '--trace-children-skip=*/sed,*/collect2,*/gcc,*/cat,*/rm,*/ls' --track-origins=yes --xml=yes --xml-file=valgrind.xml --fair-sched=try --gen-suppressions=all ./pmix_test -n 2 --test-connect
pmix_test.c:main: Test finished OK!
+ valgrind --tool=memcheck --leak-check=full --error-exitcode=0 --trace-children=yes '--trace-children-skip=*/sed,*/collect2,*/gcc,*/cat,*/rm,*/ls' --track-origins=yes --xml=yes --xml-file=valgrind.xml --fair-sched=try --gen-suppressions=all ./pmix_test -n 5 --test-resolve-peers --ns-dist 1:2:2
ERROR [pmix_test.c:157:main]: Test exited by a timeout!
ERROR [cli_stages.c:146:cli_cleanup]: rank 0 with state 1 unexpectedly terminated.
ERROR [pmix_test.c:163:main]: Test was aborted!
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-pmix-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-pmix-pr/builds/5/htmlreports/Coverity_Report
[Valgrind] Files to copy:
[Valgrind] test/valgrind.xml
[Valgrind] Copying test/valgrind.xml to /var/lib/jenkins/jobs/gh-ompi-pmix-pr/builds/5/valgrind-plugin/valgrind-results/test/valgrind.xml
[Valgrind] ERROR: failed to parse valgrind-plugin/valgrind-results/test/valgrind.xml: The element type "argv" must be terminated by the matching end-tag "</argv>".
[Valgrind] Analysing valgrind results
[Valgrind] Ending the valgrind analysis.
Setting commit status on GitHub for https://github.com/open-mpi/pmix/commit/7806bca24329dbda1f9549b790c2594d920da460
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of c0338185b6374d9847b6bd266606193faa5c41da to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr/5/ and message: 'Build finished.'
Using conext: Mellanox
```

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 1 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//6/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-pmix-pr/6/

**Comment by miked-mellanox** [comment]
valgrind report:
http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr/6/valgrindResult/

**Pull request merged**
