### PR TITLE
Set of fixes

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//37/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//38/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by artpol84** [comment]
@igor-ivanov, please note this

**Comment by rhc54** [comment]
@artpol84 I gather you folks are working on the Jenkins testing? Please let me know when it has been debugged and I'll start using it.

**Comment by artpol84** [comment]
Nope, not true yet. I'm just fixing test suite for myself. After your commit-set tests are hanging.
I mentioned Igor because he was the one who originally changed this, so he'll be aware about commit 2 in this PR.
Can you review and merge it if you're fine with the changeset.

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//39/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//40/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
