### PR TITLE
added pmix_client2 test from that can be used for mult-node configurations, set PMIX_LOCAL_PEERS by servers

### PR DESCRIPTION
**Pull request by elenash**

### CODE REVIEW

**Comment by rhc54** [comment]
Would you please correct this pull request title? I very much hope you didn't actually pull a test from the Slurm GPL repo! If you did, please delete it.

**Comment by artpol84** [comment]
Don't worry, Ralph. It was taken from my SLURM fork. And it won't go into the main trunk.

**Comment by artpol84** [comment]
Elena,
I don't think it is worth to keep 2 almost idntical client programs: pmix_client and pmix_client2. Is there any serious difference btween them?

**Comment by elenash** [comment]
Merged to one client test file.

**Comment by artpol84** [comment]
Looks OK once debug will be removed.

**Comment by elenash** [comment]
Done

**Pull request merged**
