### PR TITLE
initialize common symbols

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 this will make openmpi a bit happier

**Comment by mellanox-github** [comment]
* Coverity found 4 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//43/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rhc54** [comment]
@ggouaillardet kewl - thanks! I'll carry it upstream as well.

**Comment by rhc54** [comment]
@ggouaillardet Urrr...I meant I'll take it downstream to OMPI...

**Pull request merged**
