### PR TITLE
PMIx error handling cleanup

### PR DESCRIPTION
**Pull request by annu13**

### CODE REVIEW

**Comment by annu13** [comment]
added common dir and moved common PMIx error handling and notify functions to pmix_common.c
Made error notify common function (changed PMIx_Server_notify_error to PMIx_notify_error).
Updated comments and calls to the functions.

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//69/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//70/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//71/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by artpol84** [comment]
@rhc54  Will this go to the v1.0? or to 2.0?
We're about to start SLURM plugin submission tomorrow and I'd prefer to keep server-side API invariant if possible. Not a big deal to update plugin to support this changes but I assume that no guarantee that there will be no future modifications.

**Comment by rhc54** [comment]
I would rather not delay the plugin submission, so we’ll push this off if it impacts that timing. I hate to change APIs between versions, but perhaps that is required in this case - if we can absorb the change in time, then fine. Otherwise, we can delay the commit.

**Comment by rhc54** [comment]
Yo Artem

Let me know what you decide about this - just want to know if I should include this or not when I generate the release candidate.

**Comment by artpol84** [comment]
@rhc54  I'd say that if you sure that those changes are stable and we won't modify them in future - go ahead and merge it.

**Comment by rhc54** [comment]
Okay - let me take a closer look at it. Annu and I had met last week to discuss this and the intent was to "future-proof" that API.

**Comment by rhc54** [comment]
This looks okay - I think we'll need to do some slight cleanup to the comments in the header file, but it otherwise looks fine. Thanks Annu!

**Pull request merged**
