### PR TITLE
use fabs() with float

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//64/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rhc54** [comment]
Hmmm...the math lib is rather large, and I hate to pull it into PMIx just for this one comparison. Can't we do it some other way?

**Comment by ggouaillardet** [comment]
fabs(a-b) == ((a-b)>0)?(a-b):(b-a)
:-)

**Comment by rhc54** [comment]
I understand that - but including math.h means we have to add -lm, which
means we load the math library. My point was: why don't we just put the
code directly into that #define and avoid loading yet another library?

**Comment by ggouaillardet** [comment]
I got you point and will update the pr with a #define'd equivalent of fabs

**Comment by ggouaillardet** [comment]
i just pushed the changes to this PR so libm is no more needed

**Comment by mellanox-github** [comment]
* Coverity found 3 errors for pmix
* Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-pmix-pr//65/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
