### PR TITLE
Introduce localid's.

### PR DESCRIPTION
**Pull request by artpol84**
Introduce localid for the following purposes:
1. help resource manager to efficiently locate the process in its internal data structures.
2. distinguishing processes with the same rank.

FIXME: maybe the same might be done just on the server side by assigning callback data
to each fd?

### CODE REVIEW

**Comment by artpol84** [comment]
Ralph,
As for the FIXME in commit I have the following question:
server receives messages in  pmix_usock_recv_handler(int sd, short flags, void *cbdata) and can access the information about the peer that sent the message through its cbdata:
```C
pmix_peer_t *peer = (pmix_peer_t*)cbdata;
```
But later we discard this information and just pass the message to 
```C
void pmix_usock_process_msg(int fd, short flags, void *cbdata)
```
through ```PMIX_ACTIVATE_POST_MSG(peer->recv_msg);```
and in `pmix_usock_process_msg` we need the message header to extract the sender.

As I understand in OMPI this was done because of message routing. Do we need this functionality in PMIx? Clearly it is more robust if server relies on it's internal knowledge instead of what client sends to it.

**Comment by rhc54** [comment]
Message routing isn't required, and so we could avoid that step. See my email with comments about the refactoring in general.

**Comment by artpol84** [comment]
пятница, 27 февраля 2015 г. пользователь rhc54 написал:

> Message routing isn't required, and so we could avoid that step. See my
> email with comments about the refactoring in general.
>
>  I think that this refactoring is consistent with what you described in
the mail. If it is ok I can simplify messaging as the next step.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-mpi/pmix/pull/9#issuecomment-76386702>.
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by artpol84** [comment]
Target 2 (distinguishing processes with the same rank) is not related to RM. This is for internal PMIx usage.

**Comment by artpol84** [comment]
All changes was checked against our test suite and pass it.

**Comment by rhc54** [comment]
Sorry this has taken so long - I've gone thru several iterations trying to understand the need for the changes (which I now think I grok), identifying and cleaning up the problems, and trying to further streamline the code. I believe I've finally settled on an approach that pretty well aligns with yours, but adds some further optimization for the "non-lite" code path. Clearly, the "lite" code path is going to run a little slower as it can't be quite as efficient, but I think that's a reasonable tradeoff at this point.

I'll rebranch from your PR so I can start from a clean place again and hopefully have this committed today.

**Pull request closed without merging**
